### ISSUE TITLE
eth-ipfs-state-validator not Go 1.19 ready

### ISSUE THREAD

**Issue by ABastionOfSanity** [vulcanize/eth-ipfs-state-validator#57]
In docker build of ipld-eth-server, compilation error revealed that is not present when built on Go 1.19.

**Comment by i-norden** [comment]
I suspect it is 

```
# github.com/lucas-clemente/quic-go/internal/qtls
../../../../pkg/mod/github.com/lucas-clemente/quic-go@v0.27.1/internal/qtls/go119.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.19 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.19 yet. F...) as int value in variable declaration
```

We run into this in ipld-eth-server too if trying to build with go 1.19+

**Comment by zramsay** [comment]
rings a bell :) https://github.com/cerc-io/ipld-eth-server/issues/208

**Comment by i-norden** [comment]
I'm not sure if there is a fix, or if we should just keep using 1.18

**Comment by i-norden** [comment]
For now I suggest we continue to use 1.18 where we must, so that we can decouple fixing this issue from the ongoing rebase work.

**Comment by zramsay** [comment]
agree, though we'll need a general plan for upgrading go versions relatively synchronously across the stack, since unless we remove the dep, this will always be an issue

**Comment by ABastionOfSanity** [comment]
I checked with @srw and we are running mostly 1.19 already.

**Comment by ABastionOfSanity** [comment]
Updating ipfs/kubo to latest(0.18.1) alleviates the problem.  Go 1.19 is now necessary from geth-1.11.4

**Comment by i-norden** [comment]
Fwiw compiling geth [>-v1.11.3](https://github.com/ethereum/go-ethereum/releases/tag/v1.11.3) requires Go 1.19 but using most of the packages as dependencies (including the ones used here) does not, but it is great that this is fixed so we can advance everything to 1.19
